gateway:
  verify-hostnames: ${VERIFY_HOSTNAMES:true}
  mongodb:
    database:
      name: ${MONGODB_DATABASE_NAME}
    connection:
      string: ${MONGODB_CONNECTION_STRING}

logging:
  level:
    root: ${LOGGING_LEVEL:info}

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${JWKS_URI:https://localhost:53655/auth/.well-known/jwks.json}
