## Only create config map if it doesn't exist, otherwise write the existing values during a helm deployment.
{{- $configMap := lookup "v1" "ConfigMap" .Release.Namespace "preferences" }}
{{- $ConfigMapData := toYaml .Values.PreferencesDefaults | nindent 2 }}
{{- if $configMap }}
{{- $ConfigMapData = toYaml $configMap.data | nindent 2 }}
{{- end }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: preferences
  namespace: {{ .Release.Namespace }}
data:
  {{ $ConfigMapData }}
---
## Only create config map if it doesn't exist, otherwise write the existing values during a helm deployment.
{{- $configMapAuthKeyStore := lookup "v1" "ConfigMap" .Release.Namespace "auth-keystore" }}
{{- $configMapAuthKeyStoreData := "" }}
{{- if $configMapAuthKeyStore }}
{{- $configMapAuthKeyStoreData = $configMapAuthKeyStore.data}}
{{- end }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-keystore
  namespace: {{ .Release.Namespace }}
data:
  {{ $configMapAuthKeyStoreData }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-web-portal-config
  namespace: {{ .Release.Namespace }}
data:
  config.json: |
    {
      "bffBaseUrl": "{{ .Values.web_portal.bffUri }}",
      "bffGrafanaUrl": "/grafana",
      "verifyHttps": "{{ .Values.web_portal.verifyHttps }}",
      "environment": "{{ .Values.web_portal.environment }}"
    }
