apiVersion: batch/v1
kind: Job
metadata:
  name: integration-tests
  annotations:
    "helm.sh/hook": post-install,post-upgrade
spec:
  template:
    spec:
      containers:
        - name: {{ .Release.Name }}-integration-tests
          image: "{{ .Values.integration_tests.repository }}:{{ .Values.integration_tests.tag }}"
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: "TEST_FILTER_EXPRESSION"
              value: "{{ .Values.integration_tests.filterExpression }}"
            - name: "PREFERENCES_API_ADDRESS"
              value: "https://{{ .Release.Name}}-preferences-api-service.{{.Release.Namespace }}.svc.cluster.local:8080/preferences"
            - name: "GATEWAY_API_ADDRESS"
              value: "https://{{ .Release.Name}}-gateway-api-service.{{.Release.Namespace }}.svc.cluster.local:8080/gateway"
            - name: "AUTH_API_ADDRESS"
              value: "https://{{ .Release.Name}}-auth-api-service.{{.Release.Namespace}}.svc.cluster.local:8080/auth"
            - name: "TEMPORAL_HOST"
              value: "{{ .Release.Name}}-temporal-frontend.{{.Release.Namespace}}.svc.cluster.local:7233"
            - name: "TEMPORAL_NAMESPACE"
              value: "{{ .Values.integration_tests.temporalNamespace }}"
            - name: "KUBERNETES_NAMESPACE"
              value: "{{ .Values.integration_tests.kubernetesNamespace }}"
            - name: "MONGODB_DATABASE_NAME"
              value: "{{ .Values.env.gateway_api.mongo.databaseName }}"
            - name: "MONGODB_CONNECTION_STRING"
              value: "{{ .Values.env.gateway_api.mongo.connectionString }}"
      initContainers:
        - name: wait-for-temporal-worker
          image: busybox
          command: ['sh', '-c', 'until nslookup {{ .Release.Name}}-temporal-worker-headless.{{.Release.Namespace}}.svc.cluster.local; do echo waiting for temporal worker; sleep 2; done;']
        - name: wait-for-temporal-frontend
          image: busybox
          command: ['sh', '-c', 'until nslookup {{ .Release.Name}}-temporal-frontend.{{.Release.Namespace}}.svc.cluster.local; do echo waiting for temporal frontend; sleep 2; done;']
        - name: wait-for-email-gateway
          image: busybox
          command: ['sh', '-c', 'until nslookup {{ .Release.Name}}-email-gateway-service.{{.Release.Namespace}}.svc.cluster.local; do echo waiting for email gateway; sleep 2; done;']
        - name: wait-for-sms-gateway
          image: busybox
          command: ['sh', '-c', 'until nslookup {{ .Release.Name}}-sms-gateway-service.{{.Release.Namespace}}.svc.cluster.local; do echo waiting for sms gateway; sleep 2; done;']
        - name: wait-for-gateway-api
          image: busybox
          command: ['sh', '-c', 'until nslookup {{ .Release.Name}}-gateway-api-service.{{.Release.Namespace}}.svc.cluster.local; do echo waiting for gateway api; sleep 2; done;']
        - name: wait-for-preferences-api
          image: busybox
          command: [ 'sh', '-c', 'until nslookup {{ .Release.Name}}-preferences-api-service.{{.Release.Namespace}}.svc.cluster.local; do echo waiting for preferences api; sleep 2; done;' ]

      restartPolicy: Never
  backoffLimit: 0
