apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-temporal-db-password
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation
type: Opaque
data:
  password: "{{ .Values.env.temporal.password | b64enc }}"
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-auth-api-ssl
type: Opaque
data:
  auth-api.p12: {{ .Values.env.auth_api.ssl_keystore | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-gateway-api-ssl
type: Opaque
data:
  gateway-api.p12: {{ .Values.env.gateway_api.gateway_keystore | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-email-gateway-ssl
type: Opaque
data:
  email-gateway.p12: {{ .Values.env.email_gateway.gatewayKeystore | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-sms-gateway-ssl
type: Opaque
data:
  sms-gateway.p12: {{ .Values.env.sms_gateway.gatewayKeystore | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-preferences-api-ssl
type: Opaque
data:
  preferences-api.p12: {{ .Values.env.preferences_api.preferencesKeystore | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-schedule-api-ssl
type: Opaque
data:
  schedule-api.p12: {{ .Values.env.schedule_api.schedule_keystore | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-history-api-ssl
type: Opaque
data:
  history-api.p12: {{ .Values.env.history_api.history_keystore | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-data-converter-encryption
type: Opaque
data:
  password: {{ .Values.env.temporal.encryption.password | b64enc }}
  salt: {{ .Values.env.temporal.encryption.salt | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-gateway-api
type: Opaque
stringData:
  mongo-db-name: "{{ .Values.env.gateway_api.mongo.databaseName }}"
  mongo-db-connection-string: "{{ .Values.env.gateway_api.mongo.connectionString }}"
  keystore-password: "{{ .Values.env.gateway_api.keyStorePassword }}"
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-communication-worker
type: Opaque
stringData:
  mongo-db-name: "{{ .Values.env.communication_worker.mongo.databaseName }}"
  mongo-db-connection-string: "{{ .Values.env.communication_worker.mongo.connectionString }}"
  gateway-api-key: "{{ .Values.env.communication_worker.apiKey }}"
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-email-gateway
type: Opaque
stringData:
  sendgrid-api-key: "{{ .Values.env.email_gateway.sendgridApiKey }}"
  from-email: "{{ .Values.env.email_gateway.fromEmail }}"
  from-name: "{{ .Values.env.email_gateway.fromName }}"
  monthly-template-id: "{{ .Values.env.email_gateway.monthlyNewsletterTemplateId }}"
  user1-email: "{{ .Values.env.email_gateway.user1Email }}"
  user2-email: "{{ .Values.env.email_gateway.user2Email }}"
  history-table-name: "{{ .Values.env.email_gateway.tableName }}"
  keystore-password: "{{ .Values.env.email_gateway.keyStorePassword }}"
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-mock-gateway
type: Opaque
stringData:
  history-table-name: "{{ .Values.env.mock_gateway.tableName }}"
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-sms-gateway
type: Opaque
stringData:
  twilio-account-id: "{{ .Values.env.sms_gateway.twilioAccountSid }}"
  twilio-auth-token: "{{ .Values.env.sms_gateway.twilioAuthToken  }}"
  twilio-from-phone: "{{ .Values.env.sms_gateway.fromPhoneNumber }}"
  user1-name: "{{ .Values.env.sms_gateway.user1.name }}"
  user1-phone: "{{ .Values.env.sms_gateway.user1.phoneNumber }}"
  user2-name: "{{ .Values.env.sms_gateway.user2.name}}"
  user2-phone: "{{ .Values.env.sms_gateway.user1.phoneNumber }}"
  history-table-name: "{{ .Values.env.sms_gateway.tableName }}"
  keystore-password: "{{ .Values.env.sms_gateway.keyStorePassword }}"
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-preferences-api
type: Opaque
data:
  keystore-password: {{ .Values.env.preferences_api.keystorePassword | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-schedule-api
type: Opaque
data:
  keystore-password: {{ .Values.env.schedule_api.keyStorePassword | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-history-api
type: Opaque
data:
  keystore-password: {{ .Values.env.history_api.keyStorePassword | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-auth-api
type: Opaque
stringData:
  auth-private-key: "{{ .Values.env.auth_api.privateKey }}"
  auth-public-key: "{{ .Values.env.auth_api.publicKey }}"
  keystore-password: "{{ .Values.env.auth_api.keyStorePassword }}"
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-web-portal-bff-env
type: Opaque
data:
  PORT: {{ .Values.web_bff.port | b64enc }}
  SSL_VERIFICATION: {{ .Values.web_bff.sslVerification | b64enc }}
  AUTH_API_URL: {{ printf "https://%s-auth-api-service.%s.svc.cluster.local:8080" .Release.Name .Release.Namespace | b64enc }}
  PREFERENCES_API_URL: {{ printf "https://%s-preferences-api-service.%s.svc.cluster.local:8080/preferences" .Release.Name .Release.Namespace | b64enc }}
  GATEWAY_API_URL: {{ printf "https://%s-gateway-api-service.%s.svc.cluster.local:8080/gateway" .Release.Name .Release.Namespace | b64enc }}
  SCHEDULE_API_URL: {{ printf "https://%s-schedule-api-service.%s.svc.cluster.local:8080/schedule" .Release.Name .Release.Namespace | b64enc }}
  HISTORY_API_URL: {{ printf "https://%s-history-api-service.%s.svc.cluster.local:8080/workflow" .Release.Name .Release.Namespace | b64enc }}
  GRAFANA_API_URL: {{ printf "http://%s-grafana.%s.svc.cluster.local:80" .Release.Name .Release.Namespace | b64enc }}
  LIMIT_PERIOD_SECONDS: {{ .Values.web_bff.limitPeriodSeconds | b64enc }}
  LIMIT_NUMBER_REQUESTS: {{ .Values.web_bff.limitNumberRequests | b64enc }}
  PRIVATE_KEY: {{ .Values.env.web_portal_bff.privateKey | b64enc }}
  CERTIFICATE: {{ .Values.env.web_portal_bff.publicCrt | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-web-portal-env
type: Opaque
data:
  PRIVATE_KEY: {{ .Values.env.web_portal.privateKey | b64enc }}
  CERTIFICATE: {{ .Values.env.web_portal.publicCrt | b64enc }}
