apiVersion: v1
kind: Secret
metadata:
  name: temporal-db-password
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation
type: Opaque
data:
  password: "{{ .Values.env.temporal.password | b64enc }}"
---
apiVersion: v1
kind: Secret
metadata:
  name: auth-api-ssl
type: Opaque
data:
  auth-api.p12: {{ .Values.env.auth_api.ssl_keystore | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: gateway-api-ssl
type: Opaque
data:
  gateway-api.p12: {{ .Values.env.gateway_api.gateway_keystore | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: email-gateway-ssl
type: Opaque
data:
  email-gateway.p12: {{ .Values.env.email_gateway.gatewayKeystore | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: sms-gateway-ssl
type: Opaque
data:
  sms-gateway.p12: {{ .Values.env.sms_gateway.gatewayKeystore | quote }}
