apiVersion: v1
kind: Secret
metadata:
  name: temporal-db-password
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation
type: Opaque
data:
  password: "{{ .Values.env.temporal.password | b64enc }}"
---
apiVersion: v1
kind: Secret
metadata:
  name: auth-api-ssl
type: Opaque
data:
  auth-api.p12: {{ .Values.env.auth_api.ssk_keystore | quote }}

