apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-temporal-db-password
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation
type: Opaque
data:
  password: "{{ .Values.env.temporal.password | b64enc }}"
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-auth-api-ssl
type: Opaque
data:
  auth-api.p12: {{ .Values.env.auth_api.ssl_keystore | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-gateway-api-ssl
type: Opaque
data:
  gateway-api.p12: {{ .Values.env.gateway_api.gateway_keystore | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-email-gateway-ssl
type: Opaque
data:
  email-gateway.p12: {{ .Values.env.email_gateway.gatewayKeystore | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-sms-gateway-ssl
type: Opaque
data:
  sms-gateway.p12: {{ .Values.env.sms_gateway.gatewayKeystore | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-preferences-api-ssl
type: Opaque
data:
  preferences-api.p12: {{ .Values.env.preferences_api.preferencesKeystore | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-data-converter-encryption
type: Opaque
data:
  password: {{ .Values.env.temporal.encryption.password | b64enc }}
  salt: {{ .Values.env.temporal.encryption.salt | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-gateway-api
type: Opaque
stringData:
  mongo-db-name: "{{ .Values.env.gateway_api.mongo.databaseName }}"
  mongo-db-connection-string: "{{ .Values.env.gateway_api.mongo.connectionString }}"
  keystore-password: "{{ .Values.env.gateway_api.keyStorePassword }}"
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-communication-worker
type: Opaque
stringData:
  mongo-db-name: "{{ .Values.env.communication_worker.mongo.databaseName }}"
  mongo-db-connection-string: "{{ .Values.env.communication_worker.mongo.connectionString }}"
  gateway-api-key: "{{ .Values.env.communication_worker.apiKey }}"
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-email-gateway
type: Opaque
stringData:
  sendgrid-api-key: "{{ .Values.env.email_gateway.sendgridApiKey }}"
  from-email: "{{ .Values.env.email_gateway.fromEmail }}"
  from-name: "{{ .Values.env.email_gateway.fromName }}"
  monthly-template-id: "{{ .Values.env.email_gateway.monthlyNewsletterTemplateId }}"
  user1-email: "{{ .Values.env.email_gateway.user1Email }}"
  user2-email: "{{ .Values.env.email_gateway.user2Email }}"
  history-table-name: "{{ .Values.env.email_gateway.tableName }}"
  keystore-password: "{{ .Values.env.email_gateway.keyStorePassword }}"
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-mock-gateway
type: Opaque
stringData:
  history-table-name: "{{ .Values.env.mock_gateway.tableName }}"
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-sms-gateway
type: Opaque
stringData:
  twilio-account-id: "{{ .Values.env.sms_gateway.twilioAccountSid }}"
  twilio-auth-token: "{{ .Values.env.sms_gateway.twilioAuthToken  }}"
  twilio-from-phone: "{{ .Values.env.sms_gateway.fromPhoneNumber }}"
  user1-name: "{{ .Values.env.sms_gateway.user1.name }}"
  user1-phone: "{{ .Values.env.sms_gateway.user1.phoneNumber }}"
  user2-name: "{{ .Values.env.sms_gateway.user2.name}}"
  user2-phone: "{{ .Values.env.sms_gateway.user1.phoneNumber }}"
  history-table-name: "{{ .Values.env.sms_gateway.tableName }}"
  keystore-password: "{{ .Values.env.sms_gateway.keyStorePassword }}"
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-preferences-api
type: Opaque
data:
  keystore-password: {{ .Values.env.preferences_api.keystorePassword | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-auth-api
type: Opaque
stringData:
  auth-private-key: "{{ .Values.env.auth_api.privateKey }}"
  auth-public-key: "{{ .Values.env.auth_api.publicKey }}"
  keystore-password: "{{ .Values.env.auth_api.keyStorePassword }}"
