apiVersion: v1
kind: Secret
metadata:
  name: temporal-db-password
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded
type: Opaque
data:
  password: "{{ .Values.env.temporal.password | b64enc }}"
