apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-email-gateway-service
spec:
  selector:
    app: {{ .Release.Name }}-email-gateway
    release: {{ .Release.Name }}
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-sms-gateway-service
spec:
  selector:
    app: {{ .Release.Name }}-sms-gateway
    release: {{ .Release.Name }}
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-gateway-api-service
spec:
  selector:
    app: {{ .Release.Name }}-gateway-api
    release: {{ .Release.Name }}
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-preferences-api-service
spec:
  selector:
    app: {{ .Release.Name }}-preferences-api
    release: {{ .Release.Name }}
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-auth-api-service
spec:
  selector:
    app: {{ .Release.Name }}-auth-api
    release: {{ .Release.Name }}
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-data-converter-api-service
spec:
  selector:
    app: {{ .Release.Name }}-data-converter-api
    release: {{ .Release.Name }}
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
