{{ if .Values.email_gateway.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-email-gateway-service
spec:
  selector:
    app: {{ .Release.Name }}-email-gateway
    release: {{ .Release.Name }}
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
---
{{ end }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-mock-gateway-service
spec:
  selector:
    app: {{ .Release.Name }}-mock-gateway
    release: {{ .Release.Name }}
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
---
{{ if .Values.sms_gateway.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-sms-gateway-service
spec:
  selector:
    app: {{ .Release.Name }}-sms-gateway
    release: {{ .Release.Name }}
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
---
{{ end }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-gateway-api-service
spec:
  selector:
    app: {{ .Release.Name }}-gateway-api
    release: {{ .Release.Name }}
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-preferences-api-service
spec:
  selector:
    app: {{ .Release.Name }}-preferences-api
    release: {{ .Release.Name }}
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-auth-api-service
spec:
  selector:
    app: {{ .Release.Name }}-auth-api
    release: {{ .Release.Name }}
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-data-converter-api-service
spec:
  selector:
    app: {{ .Release.Name }}-data-converter-api
    release: {{ .Release.Name }}
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-schedule-api-service
spec:
  selector:
    app: {{ .Release.Name }}-schedule-api
    release: {{ .Release.Name }}
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-history-api-service
spec:
  selector:
    app: {{ .Release.Name }}-history-api
    release: {{ .Release.Name }}
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-web-portal-bff-service
spec:
  selector:
    app: {{ .Release.Name }}-web-portal-bff-api
    release: {{ .Release.Name }}
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-web-portal-service
spec:
  selector:
    app: {{ .Release.Name }}-web-portal
    release: {{ .Release.Name }}
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP
---
# Adapted from https://github.com/kubernetes/examples/blob/master/staging/selenium/selenium-hub-svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-selenium-hub
  labels:
    app: {{ .Release.Name }}-selenium-hub
spec:
  ports:
    - port: 4444
      targetPort: 4444
      name: port0
    - port: 4443
      targetPort: 4443
      name: port1
    - port: 4442
      targetPort: 4442
      name: port2
  selector:
    app: {{ .Release.Name }}-selenium-hub
  type: NodePort
  sessionAffinity: None
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-selenium-hub-service
  labels:
    app: {{ .Release.Name }}-selenium-hub-service
spec:
  ports:
    - port: 4444
      targetPort: 4444
      name: port0
    - port: 4443
      targetPort: 4443
      name: port1
    - port: 4442
      targetPort: 4442
      name: port2
  selector:
    app: {{ .Release.Name }}-selenium-hub
  type: ClusterIP
