apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-email-gateway-service
spec:
  selector:
    app: {{ .Release.Name }}-email-gateway
    release: {{ .Release.Name }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-sms-gateway-service
spec:
  selector:
    app: {{ .Release.Name }}-sms-gateway
    release: {{ .Release.Name }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
