@startuml GetPreferencesActivity;
|Worker|

start

:GetPreferencesFromConfigMap;

|Kubernetes Cluster|
:Returns Config Map;

|Worker|
if (Config Map?) is (ok) then
:return Preferences object;
else (error)
:return error;
endif

stop
@enduml