@startuml Send Message To Gateway Activity;
|Worker|

start

:Send UserID, workflowRunId to
Gateway URL with API key;

|Gateway|

:Check if API key is valid;
if (API key is valid) is (no) then
:return invalid status 401/403;
|Worker|
:Retry Activity;
stop
else (yes)

endif

|Gateway|
:Generate Message Contents;
:Hash message contents with workflowRunId;

:Check if messageHash exists in communication DB;
if (message already exists) is (yes) then
:return delivered status 200;
else (no)

:Sends Communication To User;

    if (message delivered?) is (yes) then
    :Stores workflowRunId, userId,
    messageHash in communication DB;
    :return delivered status 200;
    else (error)
    :return error 500;
    endif

endif
|Worker|
:Complete activity;
stop
@enduml