@startuml SendCommunicationActivity
|Temporal|
start

:Schedules Workflow;

|Worker|
partition CommunicationWorkflow {
    
    repeat
        :getSettingsActivity;
        floating note: See GetSettingsActivity.puml


    backward: Retry Activity;
    repeat while (Activity completed) is (no)

    ->yes;
    repeat
        :GetGatewayActivity;
        floating note: See GetGatewayActivity.puml

    backward: Retry Activity;
    repeat while (Activity completed) is (no)

    ->yes;
    repeat
        :SendMessageToGatewayActivity;
        floating note: See SendMessageToGatewayActivity.puml

    backward: Retry Activity;
    repeat while (Activity completed) is (no)
    ->yes;
}
|Temporal|

:Workflow Complete;
stop

@enduml