@startuml Send Message To Gateway Activity;
|Worker|

start

:Send UserID, workflowRunId to
Gateway URL with API key;

|Gateway|

:Check if API key is valid;
if (API key is valid) is (no) then
:return invalid status 401/403;
|Worker|
:Activity failed;
stop
else (yes)

endif

|Gateway|
:Generate Message Contents;
:Hash message contents with workflowRunId;

:Check if messageHash exists in communication history DB;
if (message already exists) is (yes) then
:return delivered status 200;
else (no)

:Stores workflowRunId, userId,
 messageHash in communication history DB;
:Send Communication To User;

    if (message delivered?) is (yes) then

    :return delivered status 200;
    else (error)
    :Remove message hash
    from communication DB;
    :return error 500;
    |Worker|
    :Activity failed;
    stop
    endif

endif
|Worker|
:Activity completed;
stop
@enduml
