spring.cloud.task.closecontextEnabled: true

workflow:
  gatewayId: "2cba1413-63b1-4c25-b13b-976c8794dd9b"
  userId: "stress-test-user"
  number: 100000

worker:
  taskQueue: "communication-workflow"

temporal-properties:
  encryption:
    password: ${ENCRYPTION_PASSWORD:changeme}
    salt: ${ENCRYPTION_SALT:4573c195d6593c}
