spring.cloud.task.closecontextEnabled: true

workflow:
  gatewayId: ${GATEWAY_ID}
  userId: ${USER_ID:stress-test-user}
  number: ${WORKFLOW_COUNT:1000}

worker:
  taskQueue: ${TEMPORAL_TASK_QUEUE:communication-workflow}

temporal-properties:
  encryption:
    password: ${ENCRYPTION_PASSWORD:changeme}
    salt: ${ENCRYPTION_SALT:changeme}
  namespace: ${TEMPORAL_NAMESPACE:default}
  endpoint: ${TEMPORAL_ENDPOINT:localhost:7233}
