server:
  ssl:
    key-store: ${AUTH_API_SSL_KEY_STORE:classpath:keystore/auth-api.p12}
    key-store-password: ${AUTH_API_SSL_KEY_STORE_PASSWORD}
    key-store-type: PKCS12
    enabled: true
    key-alias: auth-api
    key-password: ${AUTH_API_SSL_KEY_STORE_PASSWORD}
