@startuml Gateway Database Schema

entity GatewayDb {
    * PK - _id
    --
    * String - endpointUrl
    * String - friendlyName
    String - dateCreated (optional)
    String - description (optional)
}

@enduml
