logging:
  level:
    io.github.cameronward301.communication_scheduler.worker.communication_worker: ${WORKER_DEBUG:info}
    root: ${SPRING_DEBUG:info}

worker:
  apiKey: ${GATEWAY_API_KEY:replace-me}

web-client:
  ssl-verification: ${SSL_VERIFICATION:true}

temporal-properties:
  namespace: ${NAMESPACE:default}
  task-queue: ${TEMPORAL_TASK_QUEUE:communication-workflow}
  endpoint: ${TEMPORAL_ENDPOINT:localhost:7233}
  encryption:
    password: ${ENCRYPTION_PASSWORD:changeme}
    salt: ${ENCRYPTION_SALT:4573c195d6593c}

mongodb:
  database:
    name: ${MONGODB_DATABASE_NAME:communication-database-name}
  connection:
    string: ${MONGODB_CONNECTION_STRING:mongodb://localhost:27017}
