temporal-properties:
  namespace: ${TEMPORAL_NAMESPACE:default}
  encryption:
    password: ${ENCRYPTION_PASSWORD:change-me}
    salt: ${ENCRYPTION_SALT:change-me}
activity-properties:
  gateway-timeout-seconds: 60
logging:
  level:
    com.github.cameronward301.communication_scheduler.workflows.communication_workflow: ${WORKFLOW_LOGGING:info}
    root: ${ROOT_LOGGING:info}
