temporal-properties:
  namespace: ${TEMPORAL_NAMESPACE:default}
activity-properties:
  gateway-timeout-seconds: 60
logging:
  level:
    com.github.cameronward301.communication_scheduler.workflows.communication_workflow: ${WORKFLOW_LOGGING:info}
    root: ${ROOT_LOGGING:info}
