@startuml SystemContainerDiagram
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

LAYOUT_WITH_LEGEND()

title [Container] Communication Orchestration Platform

Person(customer, "Customer", "Customer receiving communications from a particular business")
Person(business, "Business", "Business sending communications to their customers")

System_Boundary(system, "Communication Scheduling Platform") {
    Container(temporal, "Temporal", "Container: Temporal", "Schedules workflows to send communications to customers")
    ContainerDb(gatewayDB, "Gateway Database", "Stores information about the available gateways")
    Container(platformAPI, "Communication API", "Container: Java & Spring Boot MVC")
    Container(webBFF, "Portal Backend For Frontend API (BFF)", "Container: Javascript Express Server")
    Container(webPortal, "Web Management Portal", "Container: Javascript React")
    Container(settings, "Settings Config Map", "Kubernetes Config Map")
    Container(workers, "Workers", "Container: Worker", "Runs the workflow to send the communication to the specific gateway")
    ContainerQueue(queue, "SQS Persistence Queue", "AWS SQS Queue", "Stores previously sent communications to prevent duplicates")
}


System_Ext(email_gateway, "Email Gateway")
System_Ext(sms_gateway, "SMS Gateway")

Rel(business, webPortal, "Monitors and configures platform, creates/updates/deletes customer communication schedules.", "HTTPS")
Rel(webPortal, webBFF, "Makes API calls to", "JSON/HTTPS")
Rel(webBFF, platformAPI, "Makes API calls to", "JSON/HTTPS")
Rel(platformAPI, gatewayDB, "Reads from and writes to", "SQL/TCP")
Rel(platformAPI, settings, "Reads from and writes to", "Kubernetes Java Client")
Rel(platformAPI, temporal, "Creates/Updates/Deletes scheduled workflows", "Temporal SDK")
Rel_Up(workers, temporal, "Worker polls task queue and runs workflows for sending messages users", "JSON/HTTPS")
Rel_Up(workers, gatewayDB, "Reads from", "SQL/TCP")
Rel_Up(workers, settings, "Reads from", "Kubernetes Java Client")
Rel_Down(workers, email_gateway, "Sends user ID to", "JSON/HTTPS")
Rel_Down(workers, sms_gateway, "Sends user ID to", "JSON/HTTPS")

Rel_Down(email_gateway, queue, "Reads and writes to", "JSON/HTTPS")
Rel_Down(sms_gateway, queue, "Reads and writes to", "JSON/HTTPS")

Rel_Down(email_gateway, customer, "Sends email to customer")
Rel_Down(sms_gateway, customer, "Sends sms to customer")

@enduml