@startuml Create New Workflow

participant "Temporal" as temporal
participant "Worker" as worker
database "Gateway DB" as gwdb

participant "Communication Gateway" as cgw

autonumber

worker -> temporal: Polls task queue
temporal -> temporal: Schedules workflow
worker -> worker: Starts workflow
temporal -> worker: Schedules GetSettingsActivity
worker -> worker: Get Settings
worker --> temporal: Activity completed
temporal -> worker: Schedules GetGatewayActivity
worker -> gwdb: Get gateway by id
gwdb --> worker: Returns gateway object
worker --> temporal: Activity completed
temporal -> worker: Schedules SendCommunicationActivity
worker -> cgw: Send user id and workflow run id
cgw --> worker: Returns delivery response 200 with message hash and userId
worker --> temporal: Activity completed
temporal -> worker: Complete workflow
worker --> temporal: Workflow complete
@enduml