@startuml Create New Workflow

participant "Temporal" as temporal
participant "Worker" as worker
database "Gateway DB" as gwdb
collections "Settings Config Map" as scfmp
participant "Communication Gateway" as cgw

autonumber

worker -> temporal: Polls task queue
temporal -> temporal: Schedules workflow
worker -> worker: Starts workflow
temporal -> worker: Schedules GetSettingsActivity
worker -> scfmp: Get Settings
scfmp -> worker: Returns settings
temporal -> worker: Schedules GetGatewayActivity
worker -> gwdb: Get gateway by id
gwdb -> worker: Returns gateway object
worker -> temporal: Activity completed
temporal -> worker: Schedules SendCommunicationActivity
worker -> cgw: Send user id
cgw -> worker: Returns delivery response
worker -> temporal: Activity completed
temporal -> worker: Complete workflow
worker-> temporal: Workflow complete
@enduml