openapi: 3.0.3
info:
  title: Reference Gateway API
  description: Reference Gateway API for invoking a communication gateway
  version: 1.0.0
servers:
  - url: 'https://localhost:8080/api/v1'
    description: Local development server

tags:
  - name: gateway
    description: Gateway API

paths:

  /email/newsletter:
    post:
      tags:
        - gateway
      summary: Send monthly newsletter to customer via email
      operationId: sendMonthlyNewsletterByEmail
      requestBody:
        description: The customer ID and message ID
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GatewayBody'
      responses:
        '200':
          description: OK
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '500':
          description: Internal Server Error

components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    GatewayBody:
      properties:
        userId:
          type: string
          description: The user ID of the customer
          example: 123456789
        messageId:
          type: string
          description: The message ID of the message to be sent
          example: 123456789