# Default values for helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
useAwsKubernetesSecret: true # Set to true for local kubernetes testing, false for EKS - this is managed through IAM roles.
image:
  pullPolicy: Always

temporal:
  cassandra:
    enabled: true
    config:
      cluster_size: 1

  mysql:
    enabled: false

  postgresql:
    enabled: false


  prometheus:
    enabled: true

  grafana:
    enabled: true

  elasticsearch:
    enabled: false

  schema:
    setup:
      enabled: true
    update:
      enabled: true

communication_worker:
  repository: cameronward/communication-worker
  tag: 0.1.0

PreferencesDefaults:
  GatewayTimeoutSeconds: "60"
  RetryPolicy: >-
    { "maximumAttempts": "100", "backoffCoefficient": 2, "initialInterval":
    "PT1S", "maximumInterval": "PT100S", "startToCloseTimeout": "PT10S" }