env:
  temporal:
    user: "TEMPORAL_USERNAME_HERE"
    password: "TEMPORAL_PASSWORD_HERE"
    encryption:
      password: "CREATE_ENCRYPTION_PASSWORD_HERE"
      salt: "CREATE_ENCRYPTION_SALT_HERE"

  communication_worker:
    apiKey: "CREATE_API_KEY_HERE"
    mongo:
       databaseName: "communication-scheduling-platform"
       connectionString: "MONGO_CONNECTION_STRING_HERE"

  history_db:
    tableName: "HISTORY_DB_TABLE_NAME_HERE"

  email_gateway:
    sendgridApiKey: "SENDGRID_API_KEY_HERE"
    fromEmail: "FROM_EMAIL_HERE"
    fromName: "Cameron Ward"
    monthlyNewsletterTemplateId: "TWILIO_TEMPLATE_ID_HERE"
    user1Email: "USER_1_EMAIL_HERE"
    user2Email: "USER_2_EMAIL_HERE"
    gatewayKeystore: "PASTE: gateway-api-ks-base64.txt CONTENTS HERE"
    keyStorePassword: "GATEWAY_API_KEYSTORE_PASSWORD_HERE"

  sms_gateway:
    twilioAccountSid: TWILIO_ACCOUNT_SID_HERE
    twilioAuthToken: TWILIO_AUTH_TOKEN_HERE
    fromPhoneNumber: "FROM_PHONE_NUMBER_HERE"
    user1:
      phoneNumber: "USER_1_PHONE_NUMBER_HERE" # This is the number to send the message to
      name: Cameron
    user2:
      phoneNumber: "USER_2_PHONE_NUMBER_HERE"
      name: Cameron
    gatewayKeystore: "PASTE: sms-gateway-ks-base64.txt CONTENTS HERE"
    keyStorePassword: "SMS_GATEWAY_KEYSTORE_PASSWORD_HERE"

  gateway_api:
    gateway_keystore: "PASTE: gateway-api-ks-base64.txt CONTENTS HERE"
    keyStorePassword: "GATEWAY_API_KEYSTORE_PASSWORD_HERE"
    mongo:
      databaseName: "communication-scheduling-platform" # If you have a different database name, change this
      connectionString: "MONGO_CONNECTION_STRING_HERE"

  preferences_api:
    keystorePassword: "PREFERENCES_API_KEYSTORE_PASSWORD_HERE"
    preferencesKeystore: "PASTE: preferences-api-ks-base64.txt CONTENTS HERE"

  schedule_api:
    keyStorePassword: "SCHEDULE_API_KEYSTORE_PASSWORD_HERE"
    schedule_keystore: "PASTE: schedule-api-ks-base64.txt CONTENTS HERE"

  history_api:
    keyStorePassword: "HISTORY_API_KEYSTORE_PASSWORD_HERE"
    history_keystore: "PASTE: history-api-ks-base64.txt CONTENTS HERE"

  web_portal:
    publicCrt: "PASTE: web-portal-public.crt.txt CONTENTS HERE" # Contents should look like this with \n between each block and no spaces "-----BEGIN CERTIFICATE-----\nabcd\nabcd\n==\n-----END CERTIFICATE-----"
    privateKey: "PASTE: web-portal-private.key.txt CONTENTS HERE" # Contents should look like this with \n between each block and no spaces "-----BEGIN PRIVATE KEY-----\nabcd\n\n==\n-----END PRIVATE KEY-----"

  web_portal_bff:
    publicCrt: "PASTE: bff-public.crt.txt CONTENTS HERE" # Contents should look like this with \n between each block and no spaces "-----BEGIN CERTIFICATE-----\nabcd\nabcd\n==\n-----END CERTIFICATE-----"
    privateKey: "PASTE: bff-private.key.txt CONTENTS HERE" # Contents should look like this with \n between each block and no spaces "-----BEGIN PRIVATE KEY-----\nabcd\n\n==\n-----END PRIVATE KEY-----"

  auth_api:
    publicKey: "PASTE: auth-public-key.txt CONTENTS HERE" # The contents should look like with spaces between each block and one space at the end of the string "-----BEGIN PUBLIC KEY----- abcd abcd... -----END PUBLIC KEY----- "
    privateKey: "PASTE: auth-private-key.txt CONTENTS HERE" # The contents should look like with spaces between each block and one space at the end of the string "-----BEGIN PRIVATE KEY----- abcd abcd... -----END PRIVATE KEY----- "
    keyStorePassword: "AUTH_API_KEYSTORE_PASSWORD"
    ssl_keystore: "PASTE: auth-api-ks-base64.txt CONTENTS HERE"
