# Using buildx action from: https://docs.docker.com/build/ci/github-actions/multi-platform/ and https://docs.docker.com/build/ci/github-actions/manage-tags-labels/
name: 'Build & Push Containers'
on:
  workflow_dispatch:
  push:
    paths:
      - communication-worker/**
      - email-gateway/**
      - sms-gateway/**
      - integration-tests/**
      - gateway-api/**
      - auth-api/**
      - preferences-api/**
      - data-converter-api/**
      - mock-gateway/**
      - .github/workflows/build-containers.yml
    branches:
      - "**"
    tags:
      - "v*.*.*"
  pull_request:
    branches:
      - "main"

env:
  DEPLOYMENT_NAME: cs

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        container: ["communication-worker", "email-gateway", "sms-gateway", "gateway-api", "preferences-api", "auth-api", "data-converter-api", "mock-gateway"]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Get version
        working-directory: ./${{ matrix.container }}
        run: |
          CONTAINER_VERSION=$(mvn help:evaluate -Dexpression="project.version" -q -DforceStdout)
          echo ${CONTAINER_VERSION}
          echo "CONTAINER_VERSION=${CONTAINER_VERSION}" >> $GITHUB_ENV
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.container }}
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}},value=v${{ env.CONTAINER_VERSION }}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./${{ matrix.container }}
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
  cs-integration-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Get version
        working-directory: ./integration-tests
        run: |
          CONTAINER_VERSION=$(mvn help:evaluate -Dexpression="project.version" -q -DforceStdout)
          echo ${CONTAINER_VERSION}
          echo "CONTAINER_VERSION=${CONTAINER_VERSION}" >> $GITHUB_ENV
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ secrets.DOCKERHUB_USERNAME }}/cs-integration-tests
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}},value=v${{ env.CONTAINER_VERSION }}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./integration-tests
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
#  restart-deployments:
#    runs-on: ubuntu-latest
#    needs:
#      - communication-worker
#      - email-gateway
#      - sms-gateway
#      - integration-tests
#      - gateway-api
#      - auth-api
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v4
#      - name: AWS configure
#        run: |
#          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
#          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#          aws configure set default.region eu-west-1
#          aws eks update-kubeconfig --region eu-west-1 --name communication-eks
#      - name: Encode Kubeconfig file
#        run: |
#          KUBE_CONFIG_BASE64=$(base64 -w 0 /home/runner/.kube/config)
#          echo "KUBE_CONFIG_BASE64=${KUBE_CONFIG_BASE64}" >> $GITHUB_ENV
#        shell: bash
#      - name: Setup kubectl
#        uses: tale/kubectl-action@v1
#        with:
#          base64-kube-config: ${{ env.KUBE_CONFIG_BASE64 }}
#      - name: Restart Communication Workers
#        run: kubectl rollout restart deployment/${{ env.DEPLOYMENT_NAME }}-communication-worker
#      - name: Restart Email Gateway
#        run: kubectl rollout restart deployment/${{ env.DEPLOYMENT_NAME }}-email-gateway
#      - name: Restart SMS Gateway
#        run: kubectl rollout restart deployment/${{ env.DEPLOYMENT_NAME }}-sms-gateway
#      - name: Restart Gateway API
#        run: kubectl rollout restart deployment/${{ env.DEPLOYMENT_NAME }}-gateway-api
#      - name: Restart Auth API
#        run: kubectl rollout restart deployment/${{ env.DEPLOYMENT_NAME }}-auth-api
