# Using buildx action from: https://docs.docker.com/build/ci/github-actions/multi-platform/ and https://docs.docker.com/build/ci/github-actions/manage-tags-labels/
name: 'Build & Push Node Containers'
on:
  workflow_dispatch:
  push:
    paths:
      - web-portal-bff/**
      - web-portal/**
      - .github/workflows/build-node-containers.yml
    branches:
      - "**"
    tags:
      - "v*.*.*"
  pull_request:
    branches:
      - "main"

env:
  DEPLOYMENT_NAME: cs

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        container: ["web-portal-bff", "web-portal"]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Get version
        working-directory: ./${{ matrix.container }}
        run: |
          CONTAINER_VERSION=$(node -p "require('./package.json').version")
          echo ${CONTAINER_VERSION}
          echo "CONTAINER_VERSION=${CONTAINER_VERSION}" >> $GITHUB_ENV
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ secrets.DOCKERHUB_USERNAME }}/cs-${{ matrix.container }}
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}},value=v${{ env.CONTAINER_VERSION }}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./${{ matrix.container }}
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
